<?php

namespace Conman\Resolver;


use Rhumsaa\Uuid\Uuid;

class ManifestResolver extends FileResolver {

    protected $base = 'manifests';

    public function __construct(array $args = array()) {
        if(!isset($args['id']))
            $args['id'] = Uuid::uuid4();

        parent::__construct('default', $args); // TODO: Change the autogenerated stub
    }

    public function resolve($role) {
        $this->target = $role;
        $this->applyRules($role);

        $file = $this->process($this->target, $this->file . '.manifest', 'default', 'default.manifest');

        return $file;
    }

    protected function apply($role, $target, $rule) {
        $this->file = $target;
    }


}